### ISSUE TITLE
Fragments do not parse recursively

### ISSUE THREAD

**Issue by ghost** [vanilla-jsx/vanilla-jsx#4]
Hello,

I noticed a bug in your package today while testing it out: The `Fragment()` function only parses arrays one level deep. This means that components that use a return statement like the following will render a bunch of text nodes that read "[object HTMLElement]" to the document.

```
return (
    <>
      <SingleComponent prop={value} />
      {anArrayOfComponents}
    </>
  )
```

The following worked for me to correct this:

```
exports.Fragment = ({ children } = {}) => {
  const fragment = document.createDocumentFragment();

  if (!!children) {
    const flat = flattenChildren(children)
    flat.forEach(child => {
      fragment.appendChild(child)
    })
  }

  return fragment;
}

function flattenChildren (children) {
  let flat = []
  if (Array.isArray(children)) {
    children.forEach((child) => {
      flat = flat.concat(flattenChildren(child))
    });
  } else {
    flat.push(children);
  }
  return flat
}
```

**Comment by BoltDoggy** [comment]
@vanilla-jsx/jsx-runtime@1.5.3

----

Yeah, you are right. Maybe exports.jsx has the same problem. I will carefully consider and fix the problem.

Thank you very much anyway.

**Comment by ghost** [comment]
You're welcome. Thank you for looking into the issue.
